CREATE TABLE `country` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `name` varchar(20) NOT NULL,
    `x` float NOT NULL,
    `y` float NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `country` (`id`, `name`, `x`, `y`) VALUES
    (-1, 'europe', 0, 0),
    (1, 'russia', 1368.6, 447),
    (2, 'norway', 753.9, 276.1),
    (3, 'sweden', 749.8, 366.4),
    (4, 'finland', 882.2, 272.4),
    (5, 'estonia', 865, 505.7),
    (6, 'latvia', 858.1, 555.5),
    (7, 'belarus', 911, 641.8),
    (8, 'denmark', 633, 574.9),
    (9, 'france', 507.5, 821.9),
    (10, 'netherlands', 553.2, 685),
    (11, 'germany', 635.2, 706.6),
    (12, 'kazakhstan', 1532.2, 770.9),
    (13, 'belgium', 540.5, 725.7),
    (14, 'spain', 430.6, 961.5),
    (15, 'portugal', 346.5, 968.5),
    (16, 'uk', 419.6, 612.9),
    (17, 'ireland', 341.2, 649.7),
    (18, 'iceland', 170.4, 290.5),
    (19, 'turkey', 1026.7, 979.6),
    (20, 'italy', 667.6, 916.7),
    (21, 'ukraine', 961, 773.5),
    (22, 'romania', 863.9, 831.6),
    (23, 'croatia', 730, 859.6),
    (24, 'serbia', 799.5, 875.6),
    (25, 'azerbaijan', 1220, 957.5),
    (26, 'slovenia', 705, 828.9),
    (27, 'poland', 772.5, 687.7),
    (28, 'austria', 680.6, 792.4),
    (29, 'switzerland', 599.7, 813.5),
    (30, 'bosnia_herzegovina', 748.3, 877.9),
    (31, 'cyprus', 995.7, 1057.9),
    (32, 'czech_republic', 714.2, 742.9),
    (33, 'hungary', 778.1, 805),
    (34, 'slovakia', 780.8, 770.5),
    (35, 'greece', 839.5, 993.1),
    (36, 'bulgaria', 871.5, 903.5),
    (37, 'macedonia', 813, 928),
    (38, 'albania', 788, 937.7),
    (39, 'luxembourg', 566.4, 742.9),
    (40, 'armenia', 1179.7, 958.6),
    (41, 'lithuania', 846.8, 603.5),
    (42, 'moldova', 917.6, 809.9),
    (43, 'georgia', 1153, 911.9),
    (44, 'montenegro', 775.5, 904),
    (45, 'liechtenstein', 621, 806),
    (46, 'malta', 698, 1044),
    (47, 'san_marino', 662, 879),
    (48, 'andorra', 495, 908),
    (49, 'monaco', 582.1, 883),
    (50, 'vatican', 669, 921);

CREATE TABLE `question` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `country_id` int(11) NOT NULL,
    `name` varchar(500) NOT NULL,
    `a` varchar(50) NOT NULL,
    `b` varchar(50) NOT NULL,
    `c` varchar(50) NOT NULL,
    `correct` varchar(1) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `question` (`id`, `country_id`, `name`, `a`, `b`, `c`, `correct`) VALUES
    (1, 38, 'Mis valuutat kasutab Albaania?', 'Euro', 'Lekk', 'Kroon', 'B'),
    (2, 38, 'Albaania rannajoone pikkus on?', '1250km', '531km', '362km', 'C'),
    (3, 48, 'Kes täidavad Andorra riigipea funktsiooni?', 'kaks välismaa ametikandjat', 'president', 'kuningas', 'A'),
    (4, 48, 'Andorra looduses on kirjeldatud mitut liiki kõrgemaid taimi?', '1167', '1784', '1350', 'C'),
    (5, 40, 'Millises Armeenia linnas on kõige rohkem elanike?', 'Jerevan', 'Hrazdan', 'Idževan', 'A'),
    (6, 40, 'Armeeniat ei tunnusta ainus riik maailmas', 'Läti', 'Türgi', 'Pakistan', 'C'),
    (7, 25, 'Mitu linna on Aserbaidžaanis', '3', '25', '11', 'C'),
    (8, 25, 'Mis on Aserbaidžaani telefonikood?', '994', '998', '991', 'A'),
    (9, 28, 'Viinis asub maailma vanim loomaaed. Mis aastast alates see järjepidevalt töötab?', '1652', '1752', '1852', 'B'),
    (10, 28, 'Austria saksakeelne nimi Österreich tähendab', 'Idariiki', 'Põhjariiki', 'Lääneriiki', 'A'),
    (11, 13, 'Belgia omab maailmarekordit kui kõige kauem ilma valitsuseta olnud demokraatlik ühiskond. Mitu päeva riigis puudus valitsus?', '189', '389', '589', 'C'),
    (12, 13, 'Belgia jaguneb mitmeks piirkonnaks?', '3', '4', '2', 'A'),
    (13, 30, 'Bosnia ja Hertsegoviina pealinn on?', 'Sarajevo', 'Banja Luka', 'Tuzla', 'A'),
    (14, 30, 'Millal sai Bosnia ja Hertsegoviina iseseisvaks?', '1999', '1990', '1988', 'B'),
    (15, 36, 'Mis aastast on Bulgaaria Euroopa Liidu liige', '2004', '2007', '2012', 'B'),
    (16, 36, 'Riigi suurim linn asub mis mäe jalamil?', 'Džomolungma', 'Munamäe', 'Vitosha mäe', 'C'),
    (17, 5, 'Mitu meresaart on Eestis?', '2222', '1711', '3080', 'A'),
    (18, 5, 'Eesti oli esimene riik maailmas kus toimus', '', 'Veebihääletus', '', 'B'),
    (19, 43, 'Palju inimesi elab Gruusias?', '3.72mln', '4.59mln', '2.24mln', 'A'),
    (20, 43, 'Kuidas nimetavad kohalikud oma riiki?', '', '', 'Saqartveloks', 'C'),
    (21, 14, 'Milline festival toimub Hispaanias?', 'tomati', 'kurgi', 'apelsini', 'A'),
    (22, 14, 'Hispaania nimetus pärineb sõnast Ispania. Mida see tähendab?', 'härgade maa', 'jäneste maa', 'ibeeria huntide maa', 'B'),
    (23, 23, 'Horvaadi keeles öeldakse heledajuukselise kohta plava kosa. Otsetõlkes tähendab see aga….', 'kollased juuksed', 'sinised juuksed', 'valged juuksed', 'B'),
    (24, 23, 'Horvaatias asub maailma kõige väiksem linn Hum, mitu elanikku on seal?', '100', '50', '30', 'C'),
    (25, 17, 'Milliseid järgmistest sõnadest iiri keeles ei ole?', '\"jah\" ja \"ei\"', '\"eile\" ja \"homme\"', '\"tulema\" ja \"minema\"', 'A'),
    (26, 17, 'Iirimaa kultusloomadele on pühendatud arvukalt pühi ja festivale. Mis loomad?', 'lambad', 'punahirved', 'hobused', 'C'),
    (27, 18, 'Mida tähendab Islandi pealinna nimi Reykjavík?', 'Suitsune laht', 'Voolav liustik', 'Purskav vulkaan', 'A'),
    (28, 18, 'Islandil on rohkem lambaid kui inimesi. Kui palju seal umbkaudu lambaid on?', '800 000', '8 000 000', '80 000', 'A'),
    (29, 20, 'Mille kirjutad Itaalias ametlikul dokumendil lahtrisse Firma?', 'ettevõtte nime', 'ametinime', 'allkirja', 'C'),
    (30, 20, 'Caldari di Ortona linnas asub purskkaev, milles voolab...', 'vesi', 'vein', 'õlu', 'B'),
    (31, 12, 'Mis toimus Kasahstani territooriumil esmakordselt maailmas?', 'mehitatud kosmoselennu start', 'mägironimise maailmameistrivõistlused', 'lambatassimise võistlused', 'A'),
    (32, 12, 'Kasahstani territooriumist suurima osa hõlmab...', 'mets', 'kõrb', 'veekogud', 'B'),
    (33, 35, 'Kui keegi hüüab sulle Kreekas \'Ela!\', siis mida ta sellega öelda tahab?', 'jookse', 'tule', 'osta', 'B'),
    (34, 35, 'Mitu saart on Keekas?', '2000', '4000', 'üle 6000', 'C'),
    (35, 31, 'Küprosel tähistatakse...', 'veinijoomise püha', 'Aphrodite sünnipäeva', 'suure veeuputuse päeva', 'C'),
    (36, 31, 'Pealinna Nikosia jagab pooleks nn roheline joon, mis see on?', 'rohekoridor', 'kahe riigi vaheline piir', 'trammitee', 'B'),
    (37, 41, 'Palju Leedus oleval Ristimäel on riste?', '500', '5000', '50 000', 'C'),
    (38, 41, 'Vilniuses tegutseb salajane rühmitus. Mida paigaldab see inimgrupp erinevatesse linnaosadesse?', 'kiik', 'rist', 'lipp', 'A'),
    (39, 45, 'Liechtensteinis puudub.. ', 'lennujaam', 'sõjavägi', 'nii lennujaam kui sõjavägi', 'C'),
    (40, 45, 'Ligikaudu 40% kõigist Euroopas müüdavatest ja 20% kogu maailmas toodetavatest on pärit Liechtensteinist. Mis toode?', 'parukad', 'valehambad', 'värvilised läätsed', 'B'),
    (41, 39, 'Luksemburg on tänapäeval maailmas ainus', 'jaotatud kantoniteks', 'merepiirita riik', 'suurhertsogiriik', 'C'),
    (42, 39, 'Luksemburgi ametlik nimi pärineb sõnast lucilinburch, mida see tähendab?', 'väikelinn', 'kõrge kindlus', 'taevane mägi', 'A'),
    (43, 6, 'Peategelane Läti rahvuseeposes on Lacplesis. Mida see nimi eesti keeles tähendab?', 'Vägilane', 'Vibulaskja', 'Karutapja', 'C'),
    (44, 6, 'Läti rahvuslill on...', 'rukkilill', 'harilik härjasilm', 'nurmenukk', 'B'),
    (45, 10, 'Umbes mitu km on pikk Elfstedentocht uisumaraton, mis toimub külmunud kanalitel, jõgedel ja järvedel läbides 11 linna', '200', '400', '300', 'A'),
    (46, 10, 'Mitu protsenti riigi territooriumist asub merepinnast madalamal?', '16', '26', '36', 'B'),
    (47, 37, 'Ühes turistide lemmiklinnas Ohridis on just niipalju kirikuid. ', '156', '256', '356', 'C'),
    (48, 37, 'Mis aastal Makedoonia iseseisvus? ', '1891', '1946', '1991', 'C'),
    (49, 46, 'Milleks on malta lipul \"rist\" märk?', 'Olid teises maailma sõjas meedikud', 'Tugev seos usuga', 'Polegi tähendust', 'A'),
    (50, 46, 'Kui suur on malta?', '316 km²', '816km²', '1500km²', 'A'),
    (51, 42, 'Milestii Mici veinikelder on kantud ka Guinnessi maailmrekordite raamatusse kui maailma suurim veinikelder. Umbes mitu pudelit seal hoiustatakse? ', '2 miljonit', '1 miljon', 'pool miljonit', 'A'),
    (52, 42, 'Moldova riigikeeleks on...', 'moldaavia keel', 'gagauusi keel', 'rumeenia keel', 'C'),
    (53, 49, 'Mis on see, mis Monacos on kohalikele keelatud, aga turistidele lubatud', 'tarvitada alkoholi', 'mängida kasiinos', 'ratsutada', 'B'),
    (54, 49, 'Mitu sorti roose on Prints Rainier III poolt naise mälestuseks loodud Printsess Grace roosiaias, kus on umbes 6000 roosi?', '715', '515', '315', 'C'),
    (55, 44, 'Milline riik oli esimene, kes sõlmis Montenegroga diplomaatilised suhted?', 'Serbia', 'Island', 'Eesti', 'C'),
    (56, 44, 'Kelle nimetas Montenegro 2019. aastal eestlaste hulgast oma riigi jaoks mõjukuselt kümnendaks inimeseks?', 'Aivo Orav', 'Ott Tänak', 'Kersti Kaljulaid', 'A'),
    (57, 2, 'See talispordiala on moodne variant Norra sõjaväe traditsioonilisest treeningrutiinist. Mis spordiala see on?', 'laskesuusatamine', 'kiiruisutamine', 'slaalom', 'A'),
    (58, 2, 'Mida on keelatud teha Svalbardi saartel asuvas linnas nimega Longyearbyen?', 'ilutulestikku lasta', 'koertega kelgutada', 'surra', 'C'),
    (59, 27, 'Mitu Nobeli preemiat on võitnud poolakad? ', '19', '14', '9', 'A'),
    (60, 27, 'Mille poolest on erilised Wongrowieci linnast mitte kaugel asuvad kaks jõge - Nelba ja Velna?', 'voolavad kõrvuti erinevates suundades', 'ristuvad täisnurga all', 'kulgevad paralleelselt', 'B'),
    (61, 15, 'Mida ekspordib Portugal maailmas kõige enam?', 'kitarre', 'krevette', 'korki', 'C'),
    (62, 15, 'Portugali rahvalik muusikastiil on', 'fado', 'flamenko', 'funk', 'A'),
    (63, 9, 'Millist nime on keelatud panna seale Prantsusmaal?', 'Louis', 'Napoleon', 'presidendi', 'B'),
    (64, 9, 'Prantsusmaal on Euroopa pikim mägi (Mount Elbrus). Kui pikk kõrgele see ulatub?', '3564m', '4809m', '4502m', 'B'),
    (65, 3, 'Mille maailma suurim mudel asub Rootsis? See laiub 950 km ulatuses üle Rootsi.', 'molekuli', 'päikesesüsteemi', 'raku', 'B'),
    (66, 3, 'Fika on paljude rootslaste igapäevaelu tähtsaim traditsioon. Mis on fika?', 'uinak pärast sööki', 'baari minek', 'kohvipaus', 'C'),
    (67, 22, 'Rumeenia tuntuim loss on.', 'Corvini loss', 'Dracula loss', 'Pelisori loss', 'B'),
    (68, 22, 'Rumeenias asuvad just need mäed.', 'Fitz Roy', 'mount Fuji', 'Karpaatide mäed', 'C'),
    (69, 11, 'Saksamaal on maailma suurim...', 'rongijaam', 'ujula', 'lennujaam', 'A'),
    (70, 11, 'Saksamaal on üle ... lossi.', '1200', '1800', '2100', 'C'),
    (71, 47, 'San Marino on Euroopa vanim sõltumatu riik. Mis aastast?', '301', '801', '1301', 'A'),
    (72, 47, 'San Marino on maailma ... väiksemal kohal riik', '3', '4', '5', 'C'),
    (73, 24, 'Serbia kõige populaarsem jook on...', 'Tee', 'Kohv', 'Coca Cola', 'B'),
    (74, 24, 'Serbia kõrgeim punkt on...', '2169m', '1965m', '1870m', 'A'),
    (75, 34, 'Slovakkias on ... lossi', '228', '230', '232', 'A'),
    (76, 34, 'Slovakkia pindala on...', '41 588 km²', '48 845 km²', '52 228 km²', 'B'),
    (77, 26, 'Sloveenia katab ... % maast', '~0.002%', '~0.003%', '~0.004%', 'C'),
    (78, 26, 'Sloovenias on ... koobast.', '~1000', '~10 000', '~100 000', 'B'),
    (79, 4, 'Milleks on kuulutatud Soome suuruselt kolmas linn Tampere?', 'maailma talvepealinnaks', 'maailma külmapealinnaks', 'maailma saunapealinnaks', 'C'),
    (80, 4, 'Soomet peetakse maailma ... riigiks.', 'Rikkamaks', 'rõõmsamaks', 'lahedamaks', 'B'),
    (81, 16, 'Walesis asub pikima nimega linn Euroopas, mitu tähte on linna nimes?', '48', '57', '62', 'B'),
    (82, 16, 'London oli esimene linn, mis jõudis miljoni elanikuni. Mis aastal?', '1611', '1711', '1811', 'C'),
    (83, 29, 'Šveitsis öeldaks, et sa pole kunagi kaugemal kui 10 miili mõnest järvest. Umbes mitu järve on Šveitsis?', '5000', '7000', '9000', 'B'),
    (84, 29, 'Šveits kuulus oma juustude poolest. Umbes mitut sorti juustu seal toodetakse?', '450', '350', '250', 'A'),
    (85, 8, 'See on nii Hans Christian Anderseni muinasjutt kui ka skulptuur Kopenhaagenis. Mis see on?', 'Väike merineitsi', 'Tuhkatriinu', 'Lumivalgeke', 'A'),
    (86, 8, 'Legendi kohaselt  kukkus ajal, kui Taani kuningas Valdemar II Võitja sõdis, lipp taevast alla. Kellega ta sõdis?', 'sakslastega', 'rootslastega', 'eestlastega', 'C'),
    (87, 32, 'Tänapäevase termini \'robot\' mõtles välja Josef Capek ning see tuleneb arhailise tšehhi keele sõnast \"robota\". Mida see algses keeles tähendas?', 'masin', 'ori', 'töö', 'C'),
    (88, 32, 'Kui palju losse on Tšehhis?', '~200', '~1000', '~2000', 'F'),
    (89, 19, 'Türgi presidendile Mustafa Kemalile anti 1934.aastal austav tiitel Atatürk. Mida see nimi tähendab?', 'Türgi vabastaja', 'Türgi teener', 'Türgi isa', 'C'),
    (90, 19, 'Kes nendest inimestest sündis Türgis?', 'Saint Nicholas', 'Napoleon Bonaparte', 'Karl Marx', 'A'),
    (91, 21, 'Ukraina on Euroopa suurima ... riik.', 'pindalaga', 'inimarvuga', 'võlaga', 'A'),
    (92, 21, 'Ukrainas on maailma...', 'pikim puu', 'sügavaim metroojaam', 'pikim raudtee', 'B'),
    (93, 33, 'Ungari rahvusliku lennukompanii nimi kõlab täitsa hästi ka eesti keeles. See on …', 'Kalev', 'Malev', 'Sulev', 'B'),
    (94, 33, 'Ungari tähestikus on ... tähte.', '40', '44', '45', 'B'),
    (95, 7, 'Valgevenel ...% on metsad', '0,2', '0,3', '0,4', 'C'),
    (96, 7, 'Paljun elab Valgevenes inimesi?', '~9,4 mil', '~2,4 mil', '~7,9 mil', 'C'),
    (97, 50, 'Vatikan on ainus riik, mis on täielikult ümbritsetud...', 'vallikraaviga', 'plankaiaga', 'müüriga', 'C'),
    (98, 50, 'Vatikan on maailma ... riik.', 'Vaeseim', 'Väikseim', 'Kurveim', 'B'),
    (99, 1, 'Milline nendest mängudest valmis venemaal?', 'Pacman', 'Tetris', 'Pong', 'B'),
    (100, 1, 'Maa kõige ... asustatud linn on Venemaal.', 'Külmem', 'Soojem', 'Vihmasem', 'A'),
    (101, -1, 'Mitu Euroopa riiki on kuningriigid?', '8', '10', '12', 'B'),
    (102, -1, 'Euroopas on 10 kõige lühema nimega küla. Mitu tähte on nende külade nimes?', '1', '2', '3', 'A'),
    (103, -1, 'Millise Euroopa riigi lipul on kõige enam erinevaid värve?', 'Portugal', 'Vatikan', 'Horvaatia', 'C'),
    (104, -1, 'Mitut riiki läbib Doonau jõgi?', '4', '8', '10', 'C'),
    (105, -1, 'Milline on Euroopa väikseim riik?', 'Vatikan', 'Liechtenstein', 'Monako', 'A'),
    (106, -1, 'Millisel Euroopa riigil on kõige pikem rannajoon?', 'Hispaania', 'Norra', 'Suurbritannia', 'B'),
    (107, -1, 'Umbes mitut keelt räägitakse Euroopas?', '200', '150', '100', 'A'),
    (108, -1, 'Millises riigis on kõige enam losse?', 'Suurbritannia', 'Prantsusmaa', 'Tšehhi', 'C'),
    (109, -1, 'Euroopa Kõrgeim hoone asub...', 'Suurbritannias', 'Venemaal', 'Itaalias', 'B'),
    (110, -1, 'Millist riiki peeti 2021. aastal maailma kõige õnnelikumaks?', 'Taani', 'Eesti', 'Soome', 'C'),
    (111, -1, 'Euroopa vanim ülikool asub...', 'Itaalias Bolognas ', 'Suurbritannias Oxfordis ', 'Hispaanias Salamancas', 'A'),
    (112, -1, 'Milline matkarada kulgeb Tallinnast Nidasse (Leedu)?', 'Metsa matkarada', 'Ranniku matkarada', 'Baltikumi matkarada', 'B'),
    (113, -1, 'Kuidas kutsutakse Skandinaavia legendide ja müütide järgi maailmalõpu lahingut?', 'Fimbulvetr', 'Ragnarökk', 'Valhalla', 'B'),
    (114, -1, 'Kuhu toimus teadaolevalt esimene viikingite sõjaretk?', 'Prantsusmaale', 'Venemaale', 'Inglismaale', 'C'),
    (115, -1, 'Mis nime kannab Euroopa mandriosa lõunapoolseim linn?', 'Tarifa', 'Gibraltar', 'Bolonia', 'A'),
    (116, -1, 'Milline on maailma kõige tihedamalt asustatud riik?', 'Monaco', 'San Marino', 'Luksemburg', 'A'),
    (117, -1, 'Milline on maailma põhjapoolseim miljonilinn?', 'Stockholm', 'Sankt-Peterburg', 'London', 'B'),
    (118, -1, 'Mis riik kannab selle riigi kohalikus keeles nime Hayastan?', 'Aserbaidžaan', 'Kasahstan', 'Armeenia', 'C'),
    (119, -1, 'Millisel riigil järgmistest puudub merepiir?', 'Bulgaaria', 'Moldova', 'Rumeenia', 'B'),
    (120, -1, 'Millise riigi hümn kirjutati aastatel 1568-1572, mistõttu peetakse seda vanimaks hümniks maailmas?', 'Taani', 'Madalmaad', 'Prantsusmaa', 'B'),
    (121, -1, 'Millise riigi seadusandlik kogu kannab nime Storting?', 'Austria', 'Ungari', 'Norra', 'C'),
    (122, -1, 'Euroopa kõige kallim linn (elukallidus)...', 'Genf (Šveits)', 'Pariis (Prantsusmaa)', 'Oslo (Norra)', 'A'),
    (123, -1, 'Euroopa kõige sügavam järv Hornindalsvatnet (514m) asub...', 'Rootsis', 'Norras', 'Islandil', 'B'),
    (124, -1, 'Euroopa suurima rahvaarvuga riik on Venemaa, aga mis riik on teisel kohal?', 'Saksamaa', 'Prantsusmaa', 'Türgi', 'C'),
    (125, -1, 'Euroopa pindala on ligikaudu mitu miljonit ruutkilomeetrit?', '10,2', '15,2', '20,2', 'A'),
    (126, -1, 'Euroopa pikim jõgi on...', 'Doonau', 'Volga', 'Dnepr', 'B'),
    (127, -1, 'Euroopas on 50 riiki, aga mitu riiki kuulub hetkel Euroopa Liitu?', '32', '22', '27', 'C'),
    (128, -1, 'Mitmes Euroopa riigis on käibel euro?', '15', '19', '23', 'B'),
    (129, -1, 'Euroopa nimetus pärineb...', 'Kreeka mütoloogiast', 'muinasaegsest kohanimest', 'ladina keelest', 'A'),
    (130, -1, 'Mitut protsenti maailma pindalast katab Euroopa?', '2', '7', '12', 'A'),
    (131, -1, 'Viimane riik Euroopas, mis kasutab karistusena surmanuhtlust on...', 'Venemaa', 'Valgevene', 'Türgi', 'B'),
    (132, -1, 'Maailma suurim kirik, mis mahutab 60000 inimest asub...', 'Hispaania', 'Prantsusmaa', 'Vatikan', 'C'),
    (133, -1, 'Kõige enam müüakse Euroopas šokolaadi...', 'Brüsseli lennujaamas', 'Pariisi šokolaadipoes', 'Luksemburgi šokolaadimajas', 'A'),
    (134, -1, 'Vihmamets asub...', 'Euroopas ei ole vihmametsa', 'Bosnia ja Hertsegoviinas', 'Küprosel', 'B'),
    (135, -1, 'Hispaania, Kosovo, Bosnia ja Hertsegoviina ja San Marino hümnid on sarnased ühes asjas, millises?', 'sama viis', 'kestavad alla minuti', 'puuduvad sõnad', 'C'),
    (136, -1, 'Euroopas ei ole ühtegi...', 'kõrbe', 'vihmametsa', 'vulkaani', 'A'),
    (137, -1, 'Mitu protsenti Euroopa elanikest tappis katk keskajal?', '40', '50', '60', 'C'),
    (138, -1, 'Euroopa suurima rahvaarvuga linn?', 'Moskva', 'Istanbul', 'London', 'B'),
    (139, -1, 'Etna on Euroopa aktiivseim vulkaan, mitmendal kohal on ta aga maailmas?', 'esimesel', 'teisel', 'kolmandal', 'B'),
    (140, -1, 'Teadaolevalt pikim Eestist alguse saanud jäätee oli 1323.aastal Saaremaalt...', 'Lübeckisse', 'Gdanski', 'Ventspilsi', 'A'),
    (141, -1, 'Millises Euroopa riigis ei esine sääski?', 'Maltal', 'Küprosel', 'Islandil', 'C'),
    (142, -1, 'Shakespeare’i näidendi Othello tegevus toimub', 'Inglismaal', 'Itaalias', 'Küprosel', 'C'),
    (143, -1, 'Kõige vähem külastatud riik terves Euroopas on ...', 'Moldova', 'Albaania', 'Valgevene', 'A'),
    (144, -1, 'Kõige tihedamalt asustatud riik Euroopas on...', 'San Marino', 'Monaco', 'Andorra', 'B'),
    (145, -1, 'Kus riigis asub Euroopa kõige sademeterohkeim paik, 5000 mm aastas?', 'Suurbritannias', 'Montenegros', 'Šveitsis', 'B'),
    (146, -1, 'Mis riigis asub Euroopa kõige pikem 18 km pikkune sild?', 'Portugal', 'Suurbritannia', 'Kreeka', 'A'),
    (147, -1, 'Mitmes Euroopa riigis on vasakpoolne liiklus?', '2', '4', '6', 'B'),
    (148, -1, 'Mis riigis on vanim järjepidevalt kasutusel olnud riigilipp?', 'Rootsi', 'Kreeka', 'Taani', 'C'),
    (149, -1, 'Kui hommikul öeldakse Sulle L-Ghodwa t-Tajba, mis riigis Sa siis oled?', 'Malta', 'Albaania', 'Iirimaa', 'A'),
    (150, -1, '2014 aastal eksportisid Euroopa Liidu riigid 9,1 miljonit kg midagi Qatari. Mis see oli?', 'kivid', 'puit', 'naturaalne liiv', 'C');

CREATE TABLE `leaderboard` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `name` varchar(500) NOT NULL,
    `score` int(11) NOT NULL,
    `time` int(11) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;